const { SlashCommandBuilder, EmbedBuilder, AttachmentBuilder } = require('discord.js');
const OpenAI = require('openai');
const fs = require('fs');
const path = require('path');

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

module.exports = {
  data: new SlashCommandBuilder()
    .setName('minecraftplugin')
    .setDescription('Wygeneruj plugin Minecraft za pomocą AI')
    .addStringOption(option =>
      option.setName('nazwa')
        .setDescription('Nazwa pluginu')
        .setRequired(true)
    )
    .addStringOption(option =>
      option.setName('opis')
        .setDescription('Co ma robić plugin?')
        .setRequired(true)
    )
    .addStringOption(option =>
      option.setName('wersja')
        .setDescription('Wersja Minecraft/API')
        .setRequired(false)
        .addChoices(
          { name: 'Spigot 1.20', value: 'spigot_1.20' },
          { name: 'Spigot 1.19', value: 'spigot_1.19' },
          { name: 'Paper 1.20', value: 'paper_1.20' },
          { name: 'Bukkit 1.20', value: 'bukkit_1.20' }
        )
    ),
  
  async execute(interaction) {
    const isSlash = interaction.isChatInputCommand && interaction.isChatInputCommand();
    
    if (!process.env.OPENAI_API_KEY) {
      const msg = '❌ Funkcja AI nie jest skonfigurowana! Brak klucza OpenAI API.';
      return isSlash ? await interaction.reply(msg) : interaction.reply(msg);
    }

    const pluginName = isSlash ? interaction.options.getString('nazwa') : 'MyPlugin';
    const description = isSlash ? interaction.options.getString('opis') : interaction.content.split(' ').slice(1).join(' ');
    const version = isSlash ? (interaction.options.getString('wersja') || 'spigot_1.20') : 'spigot_1.20';

    if (!description) {
      const msg = '❌ Musisz podać opis funkcjonalności pluginu!';
      return isSlash ? await interaction.reply(msg) : interaction.reply(msg);
    }

    if (isSlash) {
      await interaction.deferReply();
    } else {
      await interaction.reply('🤖 Generuję plugin Minecraft za pomocą AI... To może potrwać chwilę...');
    }

    try {
      const versionInfo = {
        'spigot_1.20': 'Spigot API 1.20.x',
        'spigot_1.19': 'Spigot API 1.19.x',
        'paper_1.20': 'Paper API 1.20.x',
        'bukkit_1.20': 'Bukkit API 1.20.x'
      };

      const prompt = `Create a complete Minecraft plugin for ${versionInfo[version]}.

Plugin Name: ${pluginName}
Description: ${description}

Generate:
1. Main plugin class (extends JavaPlugin)
2. plugin.yml configuration file
3. Command handlers
4. Event listeners (if needed)
5. Configuration file handling
6. Comments explaining the code

Requirements:
- Use proper Java conventions
- Include error handling
- Add comments for clarity
- Make it production-ready
- Follow Spigot/Bukkit best practices

Provide complete, working code that can be compiled and used immediately.`;

      const completion = await openai.chat.completions.create({
        model: "gpt-4",
        messages: [
          {
            role: "system",
            content: "You are an expert Minecraft plugin developer with deep knowledge of Spigot, Paper, and Bukkit APIs. Generate complete, working, production-ready plugins with proper code structure and documentation."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        temperature: 0.7,
        max_tokens: 3000
      });

      const pluginCode = completion.choices[0].message.content;

      const sanitizedName = pluginName.replace(/[^a-zA-Z0-9_-]/g, '_').substring(0, 50);
      const fileName = `${sanitizedName}_${Date.now()}.txt`;
      const filePath = path.join(__dirname, '..', '..', 'downloads', fileName);
      fs.writeFileSync(filePath, `# Minecraft Plugin: ${pluginName}\n# Generated by AI\n# Version: ${versionInfo[version]}\n\n${pluginCode}`);

      const embed = new EmbedBuilder()
        .setColor('#00AA00')
        .setTitle('⛏️ Wygenerowany Plugin Minecraft')
        .setDescription(`**Nazwa:** ${pluginName}\n**API:** ${versionInfo[version]}\n**Opis:** ${description}`)
        .addFields(
          { name: '🤖 Model AI', value: 'GPT-4', inline: true },
          { name: '📁 Plik', value: fileName, inline: true },
          { name: '📦 Kompilacja', value: 'Skopiuj kod do projektu Maven/Gradle', inline: false }
        )
        .setTimestamp()
        .setFooter({ text: 'Wygenerowano przez AI - Sprawdź kod przed użyciem!' });

      const preview = pluginCode.substring(0, 800);
      embed.addFields({ name: '👀 Podgląd Kodu', value: `\`\`\`java\n${preview}\n...\n\`\`\`` });

      const attachment = new AttachmentBuilder(filePath, { name: fileName });

      if (isSlash) {
        await interaction.editReply({ embeds: [embed], files: [attachment] });
      } else {
        await interaction.channel.send({ embeds: [embed], files: [attachment] });
      }

      setTimeout(() => {
        if (fs.existsSync(filePath)) {
          fs.unlinkSync(filePath);
        }
      }, 60000);

    } catch (error) {
      console.error('Generate plugin error:', error);
      
      let errorMsg = '❌ Wystąpił błąd podczas generowania pluginu!';
      if (error.status === 401) {
        errorMsg = '❌ Nieprawidłowy klucz OpenAI API!';
      } else if (error.status === 429) {
        errorMsg = '❌ Przekroczono limit zapytań do OpenAI. Spróbuj za chwilę.';
      } else if (error.message) {
        errorMsg = `❌ Błąd: ${error.message.substring(0, 100)}`;
      }

      if (isSlash) {
        if (interaction.deferred) {
          await interaction.editReply(errorMsg);
        } else {
          await interaction.reply(errorMsg);
        }
      } else {
        await interaction.channel.send(errorMsg);
      }
    }
  },
};
